name: ltai_nobet_sistemi
description: "LTAI Nöbet Planlama Sistemi — ATC vardiya yönetimi"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  intl: ^0.19.0
  firebase_core: ^2.27.0
  cloud_firestore: ^4.15.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
